apply plugin: 'com.android.application'

android {
    namespace "ohi.andre.consolelauncher"
    compileSdk 37

    def keystorePropertiesFile = rootProject.file("local.properties")
    def keystoreProperties = new Properties()
    if (keystorePropertiesFile.exists()) {
        keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
    }

    signingConfigs {
        release {
            storeFile file("../" + (keystoreProperties["storeFile"] ?: "release.jks"))
            storePassword keystoreProperties["storePassword"] ?: ""
            keyAlias keystoreProperties["keyAlias"] ?: "tui-alias"
            keyPassword keystoreProperties["keyPassword"] ?: ""
        }
    }

    defaultConfig {
        applicationId "ohi.andre.consolelauncher"
        minSdk 24
        targetSdk 37
        versionCode 302
        versionName "v6.15.1-android16-stable"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    flavorDimensions += "default"
    productFlavors {
        fdroid {
            dimension "default"
        }
        playstore {
            dimension "default"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        checkReleaseBuilds false
    }
}

dependencies {
    // AndroidX
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation 'androidx.activity:activity:1.13.0'
    implementation 'androidx.core:core:1.15.0'

    // Networking
    implementation 'com.squareup.okhttp3:okhttp:5.4.0'

    // Parsing
    implementation 'net.sourceforge.htmlcleaner:htmlcleaner:2.29'
    implementation 'com.jayway.jsonpath:json-path:3.0.0'
    implementation 'org.jsoup:jsoup:1.22.2'
    implementation 'it.andreuzzi:CompareString2:1.0.9'
}